### ISSUE TITLE
CDN mirroring currently non-functional

### ISSUE THREAD

**Issue by chrisburr** [conda-forge/status#107]
Despite the status page claiming "CDN cloning status: operational" there is an issue that is preventing new packages from being added to the CDN.

**Comment by beckermr** [comment]
This has been fixed and the system should recover in the next hour or so.

**Comment by h-vetinari** [comment]
Some files that were created during the outage are still not available, in particular, I see this with [linux-64/ecos-2.0.7.post1-py37ha757849_3.tar.bz2](https://anaconda.org/conda-forge/ecos/files). Any way to fix it besides waiting some more (or bumping the build number, as I assume the same build upon retriggering wouldn't be re-uploaded)?

**Comment by beckermr** [comment]
@chenghlee?
