### ISSUE TITLE
new package uploads not available

### ISSUE THREAD

**Issue by beckermr** [conda-forge/status#114]
Despite the positive status, the anaconda.org CDN is not syncing new packages. Thus new packages are not available. We do not currently have a timeframe for when this might be fixed.

**Comment by beckermr** [comment]
This has been addressed and should be fixed within an hour or so.

**Comment by maxnoe** [comment]
Our package is still not available. Do we have to re-upload to trigger publication? Or does it just take a while longer?

**Comment by chrisburr** [comment]
The indexing is apparently taking longer than expected so it might be another couple of hours before everything is ready. If the files show up on https://anaconda.org/conda-forge/<PACKAGE_NAME> then all will be fine once the sync finishes.

**Comment by beckermr** [comment]
The initial blocker is completed here but we are waiting for the global repodata indexing. More updates later!

**Comment by beckermr** [comment]
Looks like syncs are running again. Closing.

**Comment by maxnoe** [comment]
Just to note: one of our packages is now available (regions 0.4.0, build 3) but another is not (pyerfa 1.7.3, build 1).

So either the sync is still ongoing, or the package is an issue.

**Comment by beckermr** [comment]
@chenghlee ?

**Comment by beckermr** [comment]
I see this build for osx locally. Maybe your repodata cache is out of date?

**Comment by maxnoe** [comment]
Thanks for checking, on linux I only get the `0` builds:

```
❯ mamba clean --all --yes -q; mamba search -q -c conda-forge --override-channels pyerfa=1.7.3
WARNING: /home/maxnoe/.conda/pkgs does not exist
Loading channels: ...working... done
# Name                       Version           Build  Channel             
pyerfa                         1.7.3  py36h70b1f00_0  conda-forge         
pyerfa                         1.7.3  py36h8f6f2f9_0  conda-forge         
pyerfa                         1.7.3  py37h5e8e339_0  conda-forge         
pyerfa                         1.7.3  py37h6b43d8f_0  conda-forge         
pyerfa                         1.7.3  py38h497a2fe_0  conda-forge         
pyerfa                         1.7.3  py39h3811e60_0  conda-forge  
```

**Comment by beckermr** [comment]
I can confirm directly with the repodata that these builds are missing. 

@chenghlee can you look at this?

In the mean time, pushing a new build will likely fix it. Simply bump the build number.

**Comment by maxnoe** [comment]
@beckermr Thanks again! Will do.

**Comment by chenghlee** [comment]
Apologies for the disruption. We had a storage fault on a cloud worker that's part of the CDN sync; as part of the restoring process, we had to dump the worker's package cache, and the verify/re-download/re-index process took way longer than expected (~12 hours).

After that rebuild, several packages had still not properly re-synced to the CDN. (@maxnoe -- pyerfa 1.7.3 build 1 for Linux was among them.) We've since corrected _that_ issue, so the CDN should now be fully sync-ed.

Thanks for bearing with us while we addressed this.

**Comment by maxnoe** [comment]
Thank you very much for your efforts! Can confirm the package is now available in all versions.

**Comment by beckermr** [comment]
Thank you @chenghlee!

**Comment by tkelman** [comment]
Having another one of these outages today?

**Comment by beckermr** [comment]
yes I think so - posted a new issue here: https://github.com/conda-forge/status/issues/115
