### ISSUE TITLE
Upload validation is broken

### ISSUE THREAD

**Issue by xhochy** [conda-forge/status#165]
The validation of uploads is broken and no new packages can be uploaded at the moment.

**Comment by xhochy** [comment]
See also https://github.com/conda-forge/polars-feedstock/issues/215 cc @pavelzw

**Comment by xhochy** [comment]
Fixing https://github.com/conda-forge/conda-forge-webservices/pull/573 might help as this will trigger a redeploy of the webservice.

**Comment by beckermr** [comment]
Did you reboot the heroku server?

Also we need to check that our github apps are still ok.

**Comment by xhochy** [comment]
No, I don't have Heroku access (yet).

**Comment by beckermr** [comment]
OK. I added the major outage label. I am trying this PR: https://github.com/conda-forge/conda-forge-webservices/pull/574

No luck yet.

**Comment by beckermr** [comment]
This is fixed. closing.

**Comment by jakirkham** [comment]
Thanks Matt! 🙏

Looks like token resets are still broken

https://github.com/conda-forge/admin-requests/pull/939#issuecomment-1949941964
